### PR TITLE
Don't automatically stop the worker when all tests are done (fix compat with `ember-cli-code-coverage@v1`)

### LINKED ISSUE #23: Doesn't play nicely with `ember-cli-code-coverage`
Quick fix would be to not stop the worker when Qunit is done.

### PR DESCRIPTION
**Pull request by bertdeblock**
There seems to be a racing condition between stopping the worker and `ember-cli-code-coverage@v1` executing its `/write-coverage` call. Keeping the worker alive after the tests are done, fixes this for now.

Closes #23.

### CODE REVIEW

File: addon-test-support/index.js [hunk 1]
```diff
@@ -47,16 +45,16 @@ export function getWorker() {
   return worker;
 }
 
-function createWorker(options) {
-  worker = setupWorker();
+export function destroyWorker() {
```
Comment (bertdeblock) [inline addon-test-support/index.js:48]: Keeping this export for now so we can use it if needed.
